services:
  bid-buddy-db:
    image: postgres
    restart: always
    container_name: auctions-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres

volumes:
  postgres: